<a href="https://colab.research.google.com/github/vladgap/Various/blob/main/bdikat_tlut_mishkalim_hathalatiim-100222.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install MLNN==1.1

In [2]:
from MLNN import *
import plotly.express as px
import pandas as pd
import numpy as np
import plotly.graph_objs as go
from plotly.subplots import make_subplots
from timeit import default_timer as timer

In [3]:
data1=[
[	0	,	103	,	103	],
[	5	,	103	,	22.3	],
[	10	,	103	,	7.17	],
[	30	,	103	,	1.2	],
[	0	,	79.1	,	79.1	],
[	5	,	79.1	,	22	],
[	10	,	79.1	,	10.3	],
[	30	,	79.1	,	1.49	],
]
data1

[[0, 103, 103],
 [5, 103, 22.3],
 [10, 103, 7.17],
 [30, 103, 1.2],
 [0, 79.1, 79.1],
 [5, 79.1, 22],
 [10, 79.1, 10.3],
 [30, 79.1, 1.49]]

In [4]:
df1=pd.DataFrame(data1, columns=['t','C_in','C'])
df1

t   C_in       C
0   0  103.0  103.00
1   5  103.0   22.30
2  10  103.0    7.17
3  30  103.0    1.20
4   0   79.1   79.10
5   5   79.1   22.00
6  10   79.1   10.30
7  30   79.1    1.49

## Scaling

In [5]:
from sklearn import preprocessing

In [6]:
scaler = preprocessing.StandardScaler().fit(df1)
print(scaler.mean_, scaler.scale_)
data_scaled = scaler.transform(df1)
print (data_scaled)

[11.25 91.05 30.82] [11.38804197 11.95       36.07159513]
[[-0.98787834  1.          2.00102046]
 [-0.5488213   1.         -0.23619693]
 [-0.10976426  1.         -0.65564054]
 [ 1.6464639   1.         -0.82114472]
 [-0.98787834 -1.          1.33844927]
 [-0.5488213  -1.         -0.24451372]
 [-0.10976426 -1.         -0.56886866]
 [ 1.6464639  -1.         -0.81310516]]


In [7]:
X=data_scaled[:,0:2]
y1 = data_scaled[:,2]

In [8]:
X

array([[-0.98787834,  1.        ],
       [-0.5488213 ,  1.        ],
       [-0.10976426,  1.        ],
       [ 1.6464639 ,  1.        ],
       [-0.98787834, -1.        ],
       [-0.5488213 , -1.        ],
       [-0.10976426, -1.        ],
       [ 1.6464639 , -1.        ]])

## Finding best initials

### Initiating NN

In [9]:
layers1=[2,2,1]
reg1=Regres(layers=layers1)
reg1.set_hidden_activ('mrelu', param=0.01)

In [10]:
reg1.printWeights()


Layer 0 is the Input Layer
Layer 1 Neuron 0 : [ 0.20352131 -0.78671761 -0.64504355] mrelu
Layer 1 Neuron 1 : [ 0.15326435 -0.50064286  0.06128303] mrelu
Layer 2 Neuron 0 : [0.61172498 0.22261608 0.60325343] linear



### Full factorial

doepy

In [11]:
pip install doepy

In [12]:
from doepy import build

3 points

In [13]:
low, mid, high=-0.5, 0, 0.5
list1={
    'w1':[low, mid, high],
    'w2':[low, mid, high],
    'w3':[low, mid, high],
    'w4':[low, mid, high],
    'w5':[low, mid, high],
    'w6':[low, mid, high],
    'w7':[low, mid, high],
    'w8':[low, mid, high],
    'w9':[low, mid, high],
    # 'w10':[low, mid, high],
    # 'w11':[low, mid, high],
}

In [14]:
start = timer()
a=build.full_fact(list1) #takes 5 minutes
display(a)
end = timer()
print(end - start, 'seconds')

w1   w2   w3   w4   w5   w6   w7   w8   w9
0     -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5
1      0.0 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5
2      0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5
3     -0.5  0.0 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5
4      0.0  0.0 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5
...    ...  ...  ...  ...  ...  ...  ...  ...  ...
19678  0.0  0.0  0.5  0.5  0.5  0.5  0.5  0.5  0.5
19679  0.5  0.0  0.5  0.5  0.5  0.5  0.5  0.5  0.5
19680 -0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5
19681  0.0  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5
19682  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5

[19683 rows x 9 columns]

46.159257045999766 seconds


### Transform list to set_weights

In [15]:
def arrange_weight(layers, w_list):
    w=[]
    for i in [0,1]:
        layer=[]
        for j in range(layers[i+1]):
            neuron=w_list[(layers[i]+1)*j+i*(layers[0]+1)*layers[1]:(layers[i]+1)*(j+1)+i*(layers[0]+1)*layers[1]]
            layer.append(neuron)
        w.append(layer)
    return w    

### Creating list of lists of MSEs

get2_MSE

In [16]:
# use MultiLayerNeuron instead of Regres for saving time
layers1=[2,2,1]
mln1=MultiLayerNeuron(layers=layers1)
mln1.set_activ('mrelu', param=0.01)
mln1.set_output_activ('linear')

In [17]:
def get2_MSE1(w):
    w_arr=arrange_weight(layers1, w)
    mln1.set_weights(w_arr)
    pred=[]
    for i in range(len(X)): # rows in X
        y=[]
        for j in range(layers1[1]): # num. of neurons in hidden layer
            a=np.dot(np.append(X[i],1),mln1.network[1][j].weights)
            if a>=0:
                y.append(a)
            else:
                y.append(mln1.param*a)
        y.append(1) # the bias
        b=np.dot(y,mln1.network[2][0].weights)
        pred.append(b)
#     print (pred)    
    MSE=((2*(pred-y1))**2).sum()/len(y1)
    return MSE

3 points

In [18]:
MSEs1=[]
for i in range(len(a)):
#     MSEs1.append(get_MSE1(a.iloc[i]))
    MSEs1.append(get2_MSE1(a.iloc[i]))
    if i%10000==0:
        print (i/10000, end=' ')

0.0 1.0 

In [87]:
fig_MSE=go.Figure()
fig_MSE.add_trace(go.Scatter(y=MSEs1, mode='lines'))
fig_MSE.show()

In [20]:
MSEs1_series=pd.Series(MSEs1)
MSEs1_series

0         6.131172
1         5.513939
2         5.454575
3         5.529137
4         5.514285
           ...    
19678     9.740613
19679    11.808720
19680     9.294731
19681    10.244719
19682    12.196912
Length: 19683, dtype: float64

In [21]:
MSEs1_series_sorted=MSEs1_series.sort_values()
display(MSEs1_series_sorted.head(10))

13766    2.204254
8661     2.227900
11525    2.227900
8664     2.287261
11606    2.287261
6420     2.302745
6342     2.365333
6498     2.365333
6423     2.376107
6501     2.376107
dtype: float64

In [22]:
indexes1=MSEs1_series_sorted.index
n=10
indexes1_to_check=indexes1[:n]
indexes1_to_check

Int64Index([13766, 8661, 11525, 8664, 11606, 6420, 6342, 6498, 6423, 6501], dtype='int64')

### Checking various weight combinations

In [23]:
# w=a.iloc[175506]
# reg1.set_weights(arrange_weight(layers1, [0,0,0,0,0,0,0,0,0,0,0,0]))
# reg1.printWeights()
# print ('MSE =',get_MSE1(w))

### Choosing best weights set

In [24]:
w1_1=a.iloc[13682]
w1_2=a.iloc[8661]
print (get2_MSE1(w1_1))

3.226296261005693


In [25]:
# w0=[0,1,2,3,4,5,6,7,8,9,10]
# w1=a.iloc[103020]
w_arranged_1=arrange_weight(layers1, w1_1)

In [26]:
reg1.set_weights(w_arranged_1)
reg1.printWeights()


Layer 0 is the Input Layer
Layer 1 Neuron 0 : [ 0.5 -0.5  0.5] mrelu
Layer 1 Neuron 1 : [ 0.5 -0.5  0.5] mrelu
Layer 2 Neuron 0 : [-0.5 -0.5  0.5] linear



## Training

In [27]:
reg1=Regres(layers=layers1)
reg1.set_hidden_activ('mrelu', param=0.01)
# reg1.set_weights(w_arranged_1)

In [28]:
reg1.printWeights()


Layer 0 is the Input Layer
Layer 1 Neuron 0 : [-0.51767982 -0.43527881  0.66472406] mrelu
Layer 1 Neuron 1 : [ 0.73326904  0.69465723 -0.623542  ] mrelu
Layer 2 Neuron 0 : [-0.80421775 -0.8021634   0.72981181] linear



In [29]:
reg1.fit(np.array(X), y1, epochs=2000, eta=0.01)

Model fitted.
self.weight_history - list of lists of weights propagation
self.weight_history_table - Pandas table of weights propagation
self.MSE_history - list of MSEs propagation


In [30]:
fig=go.Figure(data=go.Scatter(y=reg1.MSE_history))#[100:]))
fig.show()

In [31]:
pred1=reg1.predict(np.array(X))
# display('predictions',pred1)

In [32]:
MSE=((2*(pred1-y1))**2).sum()/len(y1)
MSE

2.0069383369555083

In [33]:
fig2=px.scatter(x=y1,y=pred1)#, color=data.exp)
fig2.show()

In [34]:
reg1.printWeights()


Layer 0 is the Input Layer
Layer 1 Neuron 0 : [ 0.98812714 -0.23803858  1.22807947] mrelu
Layer 1 Neuron 1 : [ 0.51686221  0.91662652 -0.40157271] mrelu
Layer 2 Neuron 0 : [-0.58955763 -0.27338327  0.80166485] linear



In [35]:
reg1.weight_history[-1]

[[[0.9881271385521425, -0.23803857563075584, 1.228079470357342],
  [0.516862209330917, 0.9166265208346264, -0.40157271295852315]],
 [[-0.5895576336212551, -0.2733832698607988, 0.8016648489942767]]]

# Auto-fit

In [36]:
w=a.iloc[13766]
arr_w=arrange_weight(layers1, w)
reg_test=Regres(layers=layers1)
reg_test.set_hidden_activ('mrelu', param=0.01)
reg_test.set_weights(arr_w)
reg_test.fit(np.array(X), y1, epochs=2000, eta=0.01)
MSE_test=[get2_MSE1(w), reg_test.MSE_history[0], reg_test.MSE_history[-1]]


Model fitted.
self.weight_history - list of lists of weights propagation
self.weight_history_table - Pandas table of weights propagation
self.MSE_history - list of MSEs propagation


In [37]:
MSE_test

[2.204254174141486, 2.2709795208066064, 2.1449535139267053]

In [38]:
import sys, os

# Disable
def blockPrint():
    sys.__stdout__ = sys.stdout
    sys.stdout = open(os.devnull, 'w')

# Restore
def enablePrint():
    sys.stdout = sys.__stdout__

print ('This will print')

blockPrint()
print ("This won't")

enablePrint()
print ("This will too")

This will print
This will too


In [40]:
def get_final_MSE(w):
    # w=a.iloc[13766]
    arr_w=arrange_weight(layers1, w)
    reg_test=Regres(layers=layers1)
    reg_test.set_hidden_activ('mrelu', param=0.01)
    reg_test.set_weights(arr_w)
    reg_test.fit(np.array(X), y1, epochs=2000, eta=0.01)
    MSE_test=[get2_MSE1(w), reg_test.MSE_history[0], reg_test.MSE_history[-1]]
    return MSE_test

In [67]:
c=[]
blockPrint()
for i in range (10):
    final_MSE=get_final_MSE(a.iloc[indexes1_to_check[i]])
    b=[indexes1_to_check[i]]
    d=b+final_MSE
    c.append(d)
enablePrint()
c=np.array(c)

In [55]:
# c
# c[:,1:]

In [65]:
import random

random.randrange(1,19682)

8860

In [88]:
e=[]
blockPrint()
for i in range (20): # 20 sec for 10 runs
    rnd=random.randrange(1,19682)
    final_MSE=get_final_MSE(a.iloc[rnd])
    b=[rnd]
    d=b+final_MSE
    e.append(d)
enablePrint()
e=np.array(e)

In [89]:
# e[:,0]

In [90]:
fig_MSE.add_trace(go.Scatter(x=c[:,0],y=c[:,-1], mode='markers', marker_color='brown', showlegend=False))
fig_MSE.add_trace(go.Scatter(x=c[:,0],y=c[:,1], mode='markers', marker_color='orange', showlegend=False))

fig_MSE.add_trace(go.Scatter(x=e[:,0],y=e[:,-1], mode='markers', marker_color='black', showlegend=False))
fig_MSE.add_trace(go.Scatter(x=e[:,0],y=e[:,1], mode='markers', marker_color='green', showlegend=False))

fig_MSE.show()