<a href="https://colab.research.google.com/github/vladgap/Various/blob/main/contour_surface_by_points.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import plotly.graph_objects as go
import numpy as np

In [ ]:
n=4 # horizontal dots number. min -- 2
m=6 # vertical dots number. min --2
x=np.linspace(0,1,n)
y=np.linspace(10,20,m)
x,y = np.meshgrid(x,y)
print (x)
print (y)
z=x*y
print (z)
fig = go.Figure(data=go.Surface(x=x, y=y, z=z))
fig.update_layout(
        scene = {
            'camera_eye': {"x": 0., "y": -0.01, "z": 1.5},
            "aspectratio": {"x": 1, "y": 1, "z": 0.6},
            'camera_center': {"x": 0, "y": 0, "z": -0.1}
        },
        # width=700, height=600,
        width=1200, height=800,
        margin=dict(l=0, r=0, b=0, t=0),
)
fig.update_scenes(camera_projection_type="orthographic")

fig.show()


[[0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]]
[[10. 10. 10. 10.]
 [12. 12. 12. 12.]
 [14. 14. 14. 14.]
 [16. 16. 16. 16.]
 [18. 18. 18. 18.]
 [20. 20. 20. 20.]]
[[ 0.          3.33333333  6.66666667 10.        ]
 [ 0.          4.          8.         12.        ]
 [ 0.          4.66666667  9.33333333 14.        ]
 [ 0.          5.33333333 10.66666667 16.        ]
 [ 0.          6.         12.         18.        ]
 [ 0.          6.66666667 13.33333333 20.        ]]


In [ ]:
A=[2,30]
B=[1.5, 10]
C=[.1, 25]
D=[.8, 20]
x[0][0], y[0][0]=A[0], A[1]
x[0][n-1], y[0][n-1]=B[0], B[1]
x[m-1][0], y[m-1][0]=C[0], C[1]
x[m-1][n-1], y[m-1][n-1]=D[0], D[1]
print (x)
print (y)
# vertical boundary interpol.
for i in range(1, m-1):
  # print (i)
  x[i][0]=x[0][0]+(x[m-1][0]-x[0][0])/m*i
  x[i][n-1]=x[0][n-1]+(x[m-1][n-1]-x[0][n-1])/m*i
  y[i][0]=y[0][0]+(y[m-1][0]-y[0][0])/m*i
  y[i][n-1]=y[0][n-1]+(y[m-1][n-1]-y[0][n-1])/m*i
print (x)
print (y)
# horizontal inner interpol.
for i in range(m):
  for j in range(1, n-1):
    x[i][j]=x[i][0]+(x[i][n-1]-x[i][0])/n*j
    y[i][j]=y[i][0]+(y[i][n-1]-y[i][0])/n*j
print (x)
print (y)


[[2.         0.33333333 0.66666667 1.5       ]
 [0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]
 [0.1        0.33333333 0.66666667 0.8       ]]
[[30. 10. 10. 10.]
 [12. 12. 12. 12.]
 [14. 14. 14. 14.]
 [16. 16. 16. 16.]
 [18. 18. 18. 18.]
 [25. 20. 20. 20.]]
[[2.         0.33333333 0.66666667 1.5       ]
 [1.68333333 0.33333333 0.66666667 1.38333333]
 [1.36666667 0.33333333 0.66666667 1.26666667]
 [1.05       0.33333333 0.66666667 1.15      ]
 [0.73333333 0.33333333 0.66666667 1.03333333]
 [0.1        0.33333333 0.66666667 0.8       ]]
[[30.         10.         10.         10.        ]
 [29.16666667 12.         12.         11.66666667]
 [28.33333333 14.         14.         13.33333333]
 [27.5        16.         16.         15.        ]
 [26.66666667 18.         18.         16.66666667]
 [25.         20.         20.         20.        ]]
[[2.        

In [ ]:
z=x*y
fig = go.Figure(data=go.Surface(x=x, y=y, z=z))
fig.update_layout(
        scene = {
            'camera_eye': {"x": 0., "y": -0.01, "z": 1.5},
            "aspectratio": {"x": 1, "y": 1, "z": 0.6},
            'camera_center': {"x": 0, "y": 0, "z": -0.1}
        },
        # width=700, height=600,
        width=1200, height=800,
        margin=dict(l=0, r=0, b=0, t=0),
)
fig.update_scenes(camera_projection_type="orthographic")
print ('A=',A)
print ('B=',B)
print ('C=',C)
print ('D=',D)

fig.show()



A= [2, 30]
B= [1.5, 10]
C= [0.1, 25]
D= [0.8, 20]


# function

In [ ]:
def make_xy_grid(A, B, C, D, n=2, m=2):
  n=n # horizontal dots number. min -- 2
  m=m # vertical dots number. min --2
  x=np.linspace(0,1,n)
  y=np.linspace(0,1,m)
  x,y = np.meshgrid(x,y)

  x[0][0], y[0][0]=A[0], A[1]
  x[0][n-1], y[0][n-1]=B[0], B[1]
  x[m-1][0], y[m-1][0]=C[0], C[1]
  x[m-1][n-1], y[m-1][n-1]=D[0], D[1]
  # print (x)
  # print (y)
  # vertical boundary interpol.
  for i in range(1, m-1):
    x[i][0]=x[0][0]+(x[m-1][0]-x[0][0])/m*i
    x[i][n-1]=x[0][n-1]+(x[m-1][n-1]-x[0][n-1])/m*i
    y[i][0]=y[0][0]+(y[m-1][0]-y[0][0])/m*i
    y[i][n-1]=y[0][n-1]+(y[m-1][n-1]-y[0][n-1])/m*i
  # print (x)
  # print (y)
  # horizontal inner interpol.
  for i in range(m):
    for j in range(1, n-1):
      x[i][j]=x[i][0]+(x[i][n-1]-x[i][0])/n*j
      y[i][j]=y[i][0]+(y[i][n-1]-y[i][0])/n*j
  # print (x)
  # print (y)
  return x,y

# evaluation

In [ ]:
A=[0,10]
B=[10, 30]
C=[20,10]
D=[100,0]
x,y=make_xy_grid(A,B,C,D,4,4)
z=x*2+y

In [ ]:
x[1][2],y[1][2],z[1][2]=20,20,150
x[2][2],y[2][2],z[2][2]=20,17,130
# x[1][0],y[1][0]=100,0 #to 7

# visualization

In [ ]:
fig = go.Figure(data=go.Surface(x=x, y=y, z=z))
fig.update_layout(
        scene = {
            'camera_eye': {"x": 0., "y": -0.01, "z": 1.5},
            "aspectratio": {"x": 1, "y": 1, "z": 0.6},
            'camera_center': {"x": 0, "y": 0, "z": -0.1}
        },
        # width=700, height=600,
        width=1200, height=800,
        margin=dict(l=0, r=0, b=0, t=0),
)
fig.update_scenes(camera_projection_type="orthographic")
print ('A=',A)
print ('B=',B)
print ('C=',C)
print ('D=',D)

fig.show()

A= [0, 10]
B= [10, 30]
C= [20, 10]
D= [100, 0]


# Example - MKP

In [ ]:
A=[100,0] #7
B=[100, 35.6] #17
C=[15.69,32.15] #3
D=[15,0] #18
x1,y1=make_xy_grid(A,B,C,D,3,3)
z1=x1*0+1
x1[2][1],y1[2][1]=11.53,32.28 #6
x1[1][2],y1[1][2]=62.5,36.5 #4
x1[0][1],y1[0][1]=100,21.1 #16
x1[1][0],y1[1][0]=100,0 #to 7
x1[1][1],y1[1][1]=100,21.1 #to 16

In [ ]:
print (z1)
z1[0][0]=3029 #7
z1[0][1]=2572 #16
z1[0][2]=2092 #17
z1[1][0]=3029 #7
z1[1][1]=2572 #16
z1[1][2]=1534 #4
z1[2][0]=650 #18
z1[2][1]=496 #6
z1[2][2]=577 #3

print (z1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3029. 2572. 2092.]
 [3029. 2572. 1534.]
 [ 650.  496.  577.]]


In [ ]:
fig = go.Figure()
surf1=go.Surface(x=x1, y=y1, z=z1, opacity = 0.3)

fig.add_trace(surf1)

fig.update_layout(
        scene = {
            'camera_eye': {"x": 0., "y": -0.01, "z": 1.5},
            "aspectratio": {"x": 1, "y": 1, "z": 0.6},
            'camera_center': {"x": 0, "y": 0, "z": -0.1}
        },
        # width=700, height=600,
        width=1200, height=800,
        margin=dict(l=0, r=0, b=0, t=0),
)
fig.update_scenes(camera_projection_type="orthographic")
print ('A=',A)
print ('B=',B)
print ('C=',C)
print ('D=',D)

fig.show()

A= [100, 0]
B= [100, 35.6]
C= [15.69, 32.15]
D= [15, 0]


# 2D shape on 2D plot by 4 points

In [ ]:
import plotly.graph_objects as go

def plot_plane_2d(points):
    x, y = zip(*points, points[0])  # Add first point to the end to close the shape

    fig = go.Figure(go.Scatter(
        x=x, y=y,
        mode='lines',
        fill='toself',
        fillcolor='rgba(128, 128, 128, 0.5)',  # Grey with 0.5 opacity
        line=dict(color='rgba(128, 128, 128, 0)')  # Same color for contour
    ))

    fig.update_layout(showlegend=False)
    fig.show()

# Example usage
points = [
    (0, 0),
    (4, 1),
    (3, 3),
    (1, 2)
]

plot_plane_2d(points)

# 2D shape on 3D plot by 4 points

In [ ]:
import plotly.graph_objects as go

def plot_plane_3d(points, z=0):
    x, y = zip(*points, points[0])  # Add first point to the end to close the shape
    z = [z] * (len(points) + 1)  # Create z coordinates, one more than points for closure

    fig = go.Figure(go.Scatter3d(
        x=x, y=y, z=z,
        mode='lines',
        surfaceaxis=2,  # This tells Plotly to fill the shape
        surfacecolor='rgba(128, 128, 128, 0.5)',  # Grey with 0.5 opacity
        line=dict(color='rgba(128, 128, 128, 0.5)')  # Same color for contour
    ))

    fig.update_layout(
        scene=dict(
            aspectmode='data',
            xaxis_title='X',
            yaxis_title='Y',
            zaxis_title='Z'
        ),
        showlegend=False
    )
    fig.show()

# Example usage
points = [
    (0, 0),
    (4, 1),
    (3, 3),
    (1, 2)
]

plot_plane_3d(points, z=1)  # Plot at z=1

# 3D shape on 3D plot by 4 points

In [ ]:
import plotly.graph_objects as go

def plot_3d_volume(points, zmin=0, zmax=1):
    fig = go.Figure()

    # Base
    x, y = zip(*points, points[0])  # Add first point to the end to close the shape
    z = [zmin] * (len(points) + 1)
    fig.add_trace(go.Scatter3d(
        x=x, y=y, z=z,
        mode='lines',
        surfaceaxis=2,
        surfacecolor='rgba(128, 128, 128, 0.5)',
        line=dict(color='rgba(128, 128, 128, 0.5)')
    ))

    # Cap
    z = [zmax] * (len(points) + 1)
    fig.add_trace(go.Scatter3d(
        x=x, y=y, z=z,
        mode='lines',
        surfaceaxis=2,
        surfacecolor='rgba(128, 128, 128, 0.5)',
        line=dict(color='rgba(128, 128, 128, 0.5)')
    ))

    # Walls
    for i in range(len(points)):
        x = [points[i][0], points[(i+1)%len(points)][0], points[(i+1)%len(points)][0], points[i][0]]
        y = [points[i][1], points[(i+1)%len(points)][1], points[(i+1)%len(points)][1], points[i][1]]
        z = [zmin, zmin, zmax, zmax]
        fig.add_trace(go.Mesh3d(
            x=x, y=y, z=z,
            i=[0, 0],
            j=[1, 2],
            k=[2, 3],
            color='rgb(128, 128, 128)',
            opacity=0.5
        ))

    fig.update_layout(
        scene=dict(
            aspectmode='data',
            xaxis_title='X',
            yaxis_title='Y',
            zaxis_title='Z'
        ),
        showlegend=False
    )
    fig.show()

# Example usage
points = [
    (0, 0),
    (4, 1),
    (3, 3),
    (1, 2)
]

plot_3d_volume(points, zmin=0, zmax=2)