<a href="https://colab.research.google.com/github/vladgap/Various/blob/main/contour_surface2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import plotly.graph_objects as go
import numpy as np

x1=np.linspace(28.9,100,2)
x2=np.linspace(0,29.5,2)
u,v = np.meshgrid(x1,x2)
# u = u.flatten()
# v = v.flatten()
# print (u,v)
print (v[1][1])
print ('u=', u)
print ('v=', v)
# u[0]=np.array([90,30])
u[1][1]=90
v[1][1]=20
x=u
y=v
z=x+y
# print ("z=",z)

fig = go.Figure(go.Surface(x = x, y = y, z = z, ))
fig.update_layout(
        scene = {
            'camera_eye': {"x": 0., "y": -0.01, "z": 1.5},
            "aspectratio": {"x": 1, "y": 1, "z": 0.6},
            'camera_center': {"x": 0, "y": 0, "z": -0.1}
        },
        # width=700, height=600,
        width=1200, height=800,
        margin=dict(l=0, r=0, b=0, t=0),
)
fig.update_scenes(camera_projection_type="orthographic")

fig.show()


29.5
u= [[ 28.9 100. ]
 [ 28.9 100. ]]
v= [[ 0.   0. ]
 [29.5 29.5]]


In [3]:
x1=np.linspace(28.9,100,2)
x2=np.linspace(0,29.5,2)
u,v = np.meshgrid(x1,x2)
# u = u.flatten()
# v = v.flatten()
# print (u,v)
print (v[1][1])
print ('u=', u)
print ('v=', v)
# u[0]=np.array([90,30])
u[1][1]=90
v[1][1]=20
x=u
y=v
z=x+y
# print ("z=",z)

x=np.array([[1,5],[2,6]])
y=np.array([[0,0.5],[4,3]])
z=x*0+6

fig = go.Figure(go.Surface(x = x, y = y, z = z, ))
fig.update_layout(
        scene = {
            'camera_eye': {"x": 0., "y": -0.01, "z": 1.5},
            "aspectratio": {"x": 1, "y": 1, "z": 0.6},
            'camera_center': {"x": 0, "y": 0, "z": -0.1}
        },
        # width=700, height=600,
        width=1200, height=800,
        margin=dict(l=0, r=0, b=0, t=0),
)
fig.update_scenes(camera_projection_type="orthographic")

fig.show()


29.5
u= [[ 28.9 100. ]
 [ 28.9 100. ]]
v= [[ 0.   0. ]
 [29.5 29.5]]


In [43]:
import plotly.express as px

n,m=4,4
x=np.linspace(0,1,n)
y=np.linspace(10,20,m)
x,y = np.meshgrid(x,y)
print (x)
print (y)
z=x*y
print (z)
fig = go.Figure(data=go.Surface(x=x, y=y, z=z))
fig.update_layout(
        scene = {
            'camera_eye': {"x": 0., "y": -0.01, "z": 1.5},
            "aspectratio": {"x": 1, "y": 1, "z": 0.6},
            'camera_center': {"x": 0, "y": 0, "z": -0.1}
        },
        # width=700, height=600,
        width=1200, height=800,
        margin=dict(l=0, r=0, b=0, t=0),
)
fig.update_scenes(camera_projection_type="orthographic")

fig.show()


[[0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]]
[[10.         10.         10.         10.        ]
 [13.33333333 13.33333333 13.33333333 13.33333333]
 [16.66666667 16.66666667 16.66666667 16.66666667]
 [20.         20.         20.         20.        ]]
[[ 0.          3.33333333  6.66666667 10.        ]
 [ 0.          4.44444444  8.88888889 13.33333333]
 [ 0.          5.55555556 11.11111111 16.66666667]
 [ 0.          6.66666667 13.33333333 20.        ]]


In [45]:
A=[0.4,8]
B=[1.5, 10]
C=[.1, 25]
D=[.9, 18]
x[0][0], y[0][0]=A[0], A[1]
x[0][n-1], y[0][n-1]=B[0], B[1]
x[m-1][0], y[m-1][0]=C[0], C[1]
x[m-1][n-1], y[m-1][n-1]=D[0], D[1]
print (x)
print (y)
# vertical boundary interpol.
for i in range(1, m-1):
  # print (i)
  x[i][0]=x[0][0]+(x[m-1][0]-x[0][0])/m*i
  x[i][n-1]=x[0][n-1]+(x[m-1][n-1]-x[0][n-1])/m*i
  y[i][0]=y[0][0]+(y[m-1][0]-y[0][0])/m*i
  y[i][n-1]=y[0][n-1]+(y[m-1][n-1]-y[0][n-1])/m*i
print (x)
print (y)
# horizontal interpol.
for i in range(m):
  for j in range(1, n-1):
    x[i][j]=x[i][0]+(x[i][n-1]-x[i][0])/n*j
    y[i][j]=y[i][0]+(y[i][n-1]-y[i][0])/n*j
print (x)
print (y)


[[0.4        0.33333333 0.66666667 1.5       ]
 [0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]
 [0.1        0.33333333 0.66666667 0.9       ]]
[[ 8.         10.         10.         10.        ]
 [13.33333333 13.33333333 13.33333333 13.33333333]
 [16.66666667 16.66666667 16.66666667 16.66666667]
 [25.         20.         20.         18.        ]]
[[0.4        0.33333333 0.66666667 1.5       ]
 [0.325      0.33333333 0.66666667 1.35      ]
 [0.25       0.33333333 0.66666667 1.2       ]
 [0.1        0.33333333 0.66666667 0.9       ]]
[[ 8.         10.         10.         10.        ]
 [12.25       13.33333333 13.33333333 12.        ]
 [16.5        16.66666667 16.66666667 14.        ]
 [25.         20.         20.         18.        ]]
[[0.4     0.675   0.95    1.5    ]
 [0.325   0.58125 0.8375  1.35   ]
 [0.25    0.4875  0.725   1.2    ]
 [0.1     0.3     0.5     0.9    ]]
[[ 8.      8.5     9.     10.    ]
 [12.25   12.1875 12.125  12.    ]
 

In [46]:
z=x*y
fig = go.Figure(data=go.Surface(x=x, y=y, z=z))
fig.update_layout(
        scene = {
            'camera_eye': {"x": 0., "y": -0.01, "z": 1.5},
            "aspectratio": {"x": 1, "y": 1, "z": 0.6},
            'camera_center': {"x": 0, "y": 0, "z": -0.1}
        },
        # width=700, height=600,
        width=1200, height=800,
        margin=dict(l=0, r=0, b=0, t=0),
)
fig.update_scenes(camera_projection_type="orthographic")

fig.show()