<a href="https://colab.research.google.com/github/vladgap/Various/blob/main/contour_surface_by_points.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import plotly.graph_objects as go
import numpy as np

In [51]:
n=4 # horizontal dots number. min -- 2
m=6 # vertical dots number. min --2
x=np.linspace(0,1,n)
y=np.linspace(10,20,m)
x,y = np.meshgrid(x,y)
print (x)
print (y)
z=x*y
print (z)
fig = go.Figure(data=go.Surface(x=x, y=y, z=z))
fig.update_layout(
        scene = {
            'camera_eye': {"x": 0., "y": -0.01, "z": 1.5},
            "aspectratio": {"x": 1, "y": 1, "z": 0.6},
            'camera_center': {"x": 0, "y": 0, "z": -0.1}
        },
        # width=700, height=600,
        width=1200, height=800,
        margin=dict(l=0, r=0, b=0, t=0),
)
fig.update_scenes(camera_projection_type="orthographic")

fig.show()


[[0.  0.2 0.4 0.6 0.8 1. ]
 [0.  0.2 0.4 0.6 0.8 1. ]
 [0.  0.2 0.4 0.6 0.8 1. ]
 [0.  0.2 0.4 0.6 0.8 1. ]]
[[10.         10.         10.         10.         10.         10.        ]
 [13.33333333 13.33333333 13.33333333 13.33333333 13.33333333 13.33333333]
 [16.66666667 16.66666667 16.66666667 16.66666667 16.66666667 16.66666667]
 [20.         20.         20.         20.         20.         20.        ]]
[[ 0.          2.          4.          6.          8.         10.        ]
 [ 0.          2.66666667  5.33333333  8.         10.66666667 13.33333333]
 [ 0.          3.33333333  6.66666667 10.         13.33333333 16.66666667]
 [ 0.          4.          8.         12.         16.         20.        ]]


In [54]:
A=[2,30]
B=[1.5, 10]
C=[.1, 25]
D=[.8, 20]
x[0][0], y[0][0]=A[0], A[1]
x[0][n-1], y[0][n-1]=B[0], B[1]
x[m-1][0], y[m-1][0]=C[0], C[1]
x[m-1][n-1], y[m-1][n-1]=D[0], D[1]
print (x)
print (y)
# vertical boundary interpol.
for i in range(1, m-1):
  # print (i)
  x[i][0]=x[0][0]+(x[m-1][0]-x[0][0])/m*i
  x[i][n-1]=x[0][n-1]+(x[m-1][n-1]-x[0][n-1])/m*i
  y[i][0]=y[0][0]+(y[m-1][0]-y[0][0])/m*i
  y[i][n-1]=y[0][n-1]+(y[m-1][n-1]-y[0][n-1])/m*i
print (x)
print (y)
# horizontal inner interpol.
for i in range(m):
  for j in range(1, n-1):
    x[i][j]=x[i][0]+(x[i][n-1]-x[i][0])/n*j
    y[i][j]=y[i][0]+(y[i][n-1]-y[i][0])/n*j
print (x)
print (y)


[[2.         0.58333333 0.76666667 0.95       1.13333333 1.5       ]
 [0.325      0.49166667 0.65833333 0.825      0.99166667 1.325     ]
 [0.25       0.4        0.55       0.7        0.85       1.15      ]
 [0.1        0.21666667 0.33333333 0.45       0.56666667 0.8       ]]
[[30.          8.33333333  8.66666667  9.          9.33333333 10.        ]
 [12.25       12.29166667 12.33333333 12.375      12.41666667 12.5       ]
 [16.5        16.25       16.         15.75       15.5        15.        ]
 [25.         24.16666667 23.33333333 22.5        21.66666667 20.        ]]
[[2.         0.58333333 0.76666667 0.95       1.13333333 1.5       ]
 [1.525      0.49166667 0.65833333 0.825      0.99166667 1.325     ]
 [1.05       0.4        0.55       0.7        0.85       1.15      ]
 [0.1        0.21666667 0.33333333 0.45       0.56666667 0.8       ]]
[[30.          8.33333333  8.66666667  9.          9.33333333 10.        ]
 [28.75       12.29166667 12.33333333 12.375      12.41666667 12.5    

In [58]:
z=x*y
fig = go.Figure(data=go.Surface(x=x, y=y, z=z))
fig.update_layout(
        scene = {
            'camera_eye': {"x": 0., "y": -0.01, "z": 1.5},
            "aspectratio": {"x": 1, "y": 1, "z": 0.6},
            'camera_center': {"x": 0, "y": 0, "z": -0.1}
        },
        # width=700, height=600,
        width=1200, height=800,
        margin=dict(l=0, r=0, b=0, t=0),
)
fig.update_scenes(camera_projection_type="orthographic")
print ('A=',A)
print ('B=',B)
print ('C=',C)
print ('D=',D)

fig.show()



A= [2, 30]
B= [1.5, 10]
C= [0.1, 25]
D= [0.8, 20]


# function

In [68]:
def make_xy_grid(A, B, C, D, n=2, m=2):
  n=n # horizontal dots number. min -- 2
  m=m # vertical dots number. min --2
  x=np.linspace(0,1,n)
  y=np.linspace(0,1,m)
  x,y = np.meshgrid(x,y)

  x[0][0], y[0][0]=A[0], A[1]
  x[0][n-1], y[0][n-1]=B[0], B[1]
  x[m-1][0], y[m-1][0]=C[0], C[1]
  x[m-1][n-1], y[m-1][n-1]=D[0], D[1]
  # print (x)
  # print (y)
  # vertical boundary interpol.
  for i in range(1, m-1):
    x[i][0]=x[0][0]+(x[m-1][0]-x[0][0])/m*i
    x[i][n-1]=x[0][n-1]+(x[m-1][n-1]-x[0][n-1])/m*i
    y[i][0]=y[0][0]+(y[m-1][0]-y[0][0])/m*i
    y[i][n-1]=y[0][n-1]+(y[m-1][n-1]-y[0][n-1])/m*i
  # print (x)
  # print (y)
  # horizontal inner interpol.
  for i in range(m):
    for j in range(1, n-1):
      x[i][j]=x[i][0]+(x[i][n-1]-x[i][0])/n*j
      y[i][j]=y[i][0]+(y[i][n-1]-y[i][0])/n*j
  # print (x)
  # print (y)
  return x,y

# evaluation

In [69]:
A=[0,10]
B=[10, 30]
C=[20,10]
D=[100,0]
x,y=make_xy_grid(A,B,C,D,4,4)
z=x*2+y

# visualization

In [70]:
fig = go.Figure(data=go.Surface(x=x, y=y, z=z))
fig.update_layout(
        scene = {
            'camera_eye': {"x": 0., "y": -0.01, "z": 1.5},
            "aspectratio": {"x": 1, "y": 1, "z": 0.6},
            'camera_center': {"x": 0, "y": 0, "z": -0.1}
        },
        # width=700, height=600,
        width=1200, height=800,
        margin=dict(l=0, r=0, b=0, t=0),
)
fig.update_scenes(camera_projection_type="orthographic")
print ('A=',A)
print ('B=',B)
print ('C=',C)
print ('D=',D)

fig.show()

A= [0, 10]
B= [10, 30]
C= [20, 10]
D= [100, 0]
