<a href="https://colab.research.google.com/github/vladgap/Various/blob/main/MiddleData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import plotly.graph_objs as go

#### MiddleData

In [2]:
data_orig=[]
for x in [1,2,3,4,5]:
  for y in [6,7,8,9]:
    data_orig.append([x,y,x*y])
data_orig=np.array(data_orig)
data_orig

array([[ 1,  6,  6],
       [ 1,  7,  7],
       [ 1,  8,  8],
       [ 1,  9,  9],
       [ 2,  6, 12],
       [ 2,  7, 14],
       [ 2,  8, 16],
       [ 2,  9, 18],
       [ 3,  6, 18],
       [ 3,  7, 21],
       [ 3,  8, 24],
       [ 3,  9, 27],
       [ 4,  6, 24],
       [ 4,  7, 28],
       [ 4,  8, 32],
       [ 4,  9, 36],
       [ 5,  6, 30],
       [ 5,  7, 35],
       [ 5,  8, 40],
       [ 5,  9, 45]])

In [3]:
rows=len(set(data_orig[:,1]))
cols=len(set(data_orig[:,0]))

In [4]:
col_x=np.array([sorted(set(data_orig[:,0]))]*4)
col_x

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [5]:
col_y=np.array([sorted(set(data_orig[:,1]))]*5).T
col_y

array([[6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9]])

In [6]:
data_dict={}
for row in range(len(data_orig)):
  data_dict.update({(data_orig[row,0],data_orig[row,1]):data_orig[row,2]})
# data_dict
# data_dict[2,7]

In [7]:
col_z=col_x.copy()
for row in range(rows):
  for col in range(cols):
    col_z[row,col]=data_dict[col_x[row,col],col_y[row,col]]
col_z

array([[ 6, 12, 18, 24, 30],
       [ 7, 14, 21, 28, 35],
       [ 8, 16, 24, 32, 40],
       [ 9, 18, 27, 36, 45]])

In [8]:
class MiddleData:
  '''
  '''
  def __init__(self, input_array):
    data_orig=np.array(input_array)
    rows=len(set(data_orig[:,1]))
    cols=len(set(data_orig[:,0]))
    col_x=np.array([sorted(set(data_orig[:,0]))]*rows)
    col_y=np.array([sorted(set(data_orig[:,1]))]*cols).T
    data_dict={}
    for row in range(len(data_orig)):
      data_dict.update({(data_orig[row,0],data_orig[row,1]):data_orig[row,2]})
    col_z=col_x.copy()
    for row in range(rows):
      for col in range(cols):
        col_z[row,col]=data_dict[col_x[row,col],col_y[row,col]]

    def MiddleMatrix(matrix):
      B1=matrix[:-1,:-1]
      B2=matrix[1:,:-1]
      B3=matrix[:-1,1:]
      B4=matrix[1:,1:]
      output_matrix=(B1+B2+B3+B4)/4.
      return output_matrix

    Xm=MiddleMatrix(col_x).flatten()
    Ym=MiddleMatrix(col_y).flatten()
    Zm=MiddleMatrix(col_z).flatten()

    self.output_array=np.concatenate(([Xm],[Ym],[Zm]),axis=0).T

In [9]:
mid=MiddleData(data_orig).output_array
mid

array([[ 1.5 ,  6.5 ,  9.75],
       [ 2.5 ,  6.5 , 16.25],
       [ 3.5 ,  6.5 , 22.75],
       [ 4.5 ,  6.5 , 29.25],
       [ 1.5 ,  7.5 , 11.25],
       [ 2.5 ,  7.5 , 18.75],
       [ 3.5 ,  7.5 , 26.25],
       [ 4.5 ,  7.5 , 33.75],
       [ 1.5 ,  8.5 , 12.75],
       [ 2.5 ,  8.5 , 21.25],
       [ 3.5 ,  8.5 , 29.75],
       [ 4.5 ,  8.5 , 38.25]])

In [10]:
fig=go.Figure()
fig.add_trace(go.Scatter3d(x=data_orig[:,0], y=data_orig[:,1], z=data_orig[:,2], mode = "markers", name='data_orig'))
fig.add_trace(go.Scatter3d(x=mid[:,0], y=mid[:,1], z=mid[:,2], mode = "markers", name='data_middle'))
fig.show()